// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxl4nKA0hrVzk6UV4qQmIwZ95-k1uxX0s',
    appId: '1:599922435044:android:17e13985ebf0330fa81df1',
    messagingSenderId: '599922435044',
    projectId: 'teethkids-97abb',
    databaseURL: 'https://teethkids-97abb-default-rtdb.firebaseio.com',
    storageBucket: 'teethkids-97abb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmCzkrUjmN9jlv5jz7nP5hztJA5txvNR4',
    appId: '1:599922435044:ios:c6530ed047ae178da81df1',
    messagingSenderId: '599922435044',
    projectId: 'teethkids-97abb',
    databaseURL: 'https://teethkids-97abb-default-rtdb.firebaseio.com',
    storageBucket: 'teethkids-97abb.appspot.com',
    androidClientId: '599922435044-1u36rqdn2v5pfie52b7gvlb5naagusbq.apps.googleusercontent.com',
    iosClientId: '599922435044-muamvtrpui4sdn1fu2vtcfb4s0k69vat.apps.googleusercontent.com',
    iosBundleId: 'com.example.teethkidsflutter.teethKidsFlutter',
  );
}
